import type { SiteContent } from '@models/SiteContent.type';

export const SITE_CONTENT: SiteContent = {
  hero: {
    tag: "THE OFFLINE WALLET FOR YOUR CRYPTO",
    title: "YOUR CRYPTO, SAFE IN YOUR POCKET.",
    description: "Stasher is a small device that keeps your crypto safe. Think of it as a vault you carry. It never goes online, so hackers cannot reach it. You press a button on the device to approve every move. Built to stay safe for decades, even against future super-computers.",
    cta: "GET STASHER",
    networkLoad: "0.042 MS/S"
  },

  stats: {
    items: [
      { value: "56+", label: "Coins You Can Store" },
      { value: "0", label: "Times Hacked" },
      { value: "100%", label: "Offline and Safe" },
      { value: "FUTURE", label: "Proof Against New Attacks" }
    ]
  },

  architecture: {
    title: "HOW STASHER KEEPS YOUR CRYPTO SAFE",
    subtitle: "How It Works",
    description: "Two small devices work together. One holds your money and stays offline. The other helps it talk to the internet, without ever seeing your secrets. Your money and the internet never share the same wire.",
    zones: [
      {
        zone: "OFFLINE DEVICE",
        color: "var(--accent-cyan)",
        machines: [
          { name: "THE VAULT", role: "Where Your Money Lives", detail: "Your crypto is created and kept here. Nothing ever leaves this device. It is completely offline — no WiFi, no Bluetooth, no internet." },
          { name: "THE LOCK", role: "Future-Proof Protection", detail: "Locks your crypto with next-generation math that stays safe against today's hackers AND future super-computers that will break old-style locks." }
        ]
      },
      {
        zone: "BRIDGE DEVICE",
        color: "var(--accent-yellow)",
        machines: [
          { name: "THE MESSENGER", role: "The Go-Between", detail: "This one talks to the internet. It sends your approved transactions and brings back balance updates. It never sees your secrets." }
        ]
      },
      {
        zone: "PHONE APP",
        color: "var(--accent-blue)",
        machines: [
          { name: "STASHER APP", role: "Your Everyday Screen", detail: "A friendly app for iPhone and Android. See your coins, start transactions, and connect to your Stasher — all in one place." }
        ]
      }
    ]
  },

  security: {
    title: "BUILT LIKE A VAULT",
    subtitle: "Why It's Safe",
    description: "Every layer is designed so that even if something goes wrong, your crypto stays yours. Your secrets never leave the device. Even if your phone gets hacked, your crypto is fine.",
    features: [
      {
        id: "01",
        title: "Never Online",
        description: "The part of Stasher that holds your money has no internet, no Bluetooth, no WiFi. Hackers on the other side of the world cannot reach it — because it is simply not connected to anything.",
        icon: "AIRGAP"
      },
      {
        id: "02",
        title: "Future-Proof Protection",
        description: "Stasher uses next-generation security that stays strong even against future super-powerful computers (called quantum computers) that experts say will break regular security in the coming years.",
        icon: "QUANTUM"
      },
      {
        id: "03",
        title: "Your Backup Is Locked",
        description: "Your 24-word backup phrase is locked inside the device with your password. Nobody can pull it out — not thieves, not strangers, not even us at Stasher.",
        icon: "AES256"
      },
      {
        id: "04",
        title: "Truly Unique Keys",
        description: "Your wallet is built with truly random numbers generated by the device itself. No patterns. No shortcuts. Every Stasher wallet is one-of-a-kind and impossible to guess.",
        icon: "TRNG"
      },
      {
        id: "05",
        title: "You See Every Move",
        description: "Before anything sends, the Stasher screen shows you exactly what is about to happen. You press the button on the device to approve. No surprises, no tricks.",
        icon: "VERIFY"
      },
      {
        id: "06",
        title: "Locks Out Thieves",
        description: "If someone finds your Stasher, it locks them out after a few wrong password tries — first for seconds, then hours, then a full day. Plenty of time for you to rescue your crypto with your backup phrase.",
        icon: "LOCK"
      }
    ]
  },

  howItWorks: {
    title: "SENDING CRYPTO IS JUST EIGHT STEPS",
    subtitle: "How Sending Works",
    steps: [
      { step: 1, label: "PICK", description: "Open the Stasher app on your phone. Choose how much you want to send and who gets it.", zone: "hot" },
      { step: 2, label: "SEND", description: "Your phone passes the details to your Stasher device — like pairing headphones, but private.", zone: "dmz" },
      { step: 3, label: "REVIEW", description: "The Stasher screen shows the exact details so you can check them yourself.", zone: "cold" },
      { step: 4, label: "APPROVE", description: "Press the button on the device to say yes. Nothing moves without your press.", zone: "cold" },
      { step: 5, label: "SIGN", description: "Stasher approves the transaction inside itself using future-proof security. Your secret never leaves the device.", zone: "cold" },
      { step: 6, label: "RELAY", description: "The approved transaction goes to the bridge device that talks to the internet.", zone: "dmz" },
      { step: 7, label: "BROADCAST", description: "The bridge sends the transaction out to the world so your coins actually move.", zone: "hot" },
      { step: 8, label: "DONE", description: "Your phone shows 'sent!' The money moved. Your secrets stayed safe.", zone: "hot" }
    ]
  },

  differentiators: {
    title: "WHY STASHER",
    items: [
      {
        id: "01",
        label: "OFFLINE",
        title: "Always Offline",
        description: "Other wallets plug into your phone or computer when they sign — for a moment, your crypto is close to the internet. The Stasher device holding your money never connects to anything. Hackers cannot reach what is not online. Not even Stasher can."
      },
      {
        id: "02",
        label: "FUTURE-PROOF",
        title: "Quantum-Safe",
        description: "Experts say powerful new computers (called quantum computers) will break old-style encryption within the next decade. Stasher is one of the first wallets built to survive them. Your crypto stays safe now AND later — no panic upgrade."
      },
      {
        id: "03",
        label: "TWO-PART",
        title: "Two Devices Working As One",
        description: "One device guards your crypto. The other talks to the internet. They pass messages, never secrets. A setup other wallets don't have — your money and the web never share the same wire."
      },
      {
        id: "04",
        label: "MANY COINS",
        title: "56+ Coins on One Device",
        description: "Bitcoin, Ethereum, Solana, and 50+ others — all held on one small device. Lose it? A simple 24-word backup phrase restores everything, on any compatible wallet."
      }
    ]
  },

  products: {
    title: "FROM YOUR POCKET TO A COMPANY VAULT",
    subtitle: "Two Versions",
    tiers: [
      {
        id: "consumer",
        name: "STASHER",
        tagline: "The Personal Crypto Safe",
        highlight: true,
        features: [
          "Perfect for first-time buyers, long-term savers, traders, and families",
          "Keeps your crypto offline where hackers cannot reach it",
          "Works with 56+ popular coins: Bitcoin, Ethereum, Solana, and more",
          "Built to stay safe against future super-computers",
          "Free app for iPhone and Android",
          "Simple 24-word backup — if you lose the device, you recover everything",
          "Small screen and button so you see and approve every transaction",
          "Password-protected and locks itself against thieves",
          "You own your crypto — Stasher has no access to it, ever",
          "Works the same even if Stasher the company disappeared"
        ]
      },
      {
        id: "enterprise",
        name: "STASHER ENTERPRISE",
        tagline: "For Companies, Exchanges, and Wealthy Families",
        features: [
          "Six coordinated devices guard the crypto together",
          "Future-proof, quantum-safe security",
          "No single machine knows the whole secret — split in three parts",
          "Offline signing with a secure bridge to the internet",
          "Team approval: one person proposes, another confirms",
          "Set rules like '3 of 5 people must approve'",
          "Tamper-proof audit log of every action",
          "Strong login with password + security key",
          "Live dashboards and enterprise-ready deployment",
          "Supports Bitcoin, Ethereum, Solana, XRP, Polkadot, and more"
        ]
      }
    ]
  },

  appShowcase: {
    title: "THE STASHER APP",
    subtitle: "Your Everyday Screen",
    description: "A friendly phone app that shows all your crypto in one place. Send money to a friend, pay someone, or move funds around — a few taps and a press on the Stasher device, and you are done. Your crypto stays safe on the device. Your phone just helps you use it.",
    features: [
      { title: "All Your Coins in One Place", description: "See every coin you own in one clear dashboard with up-to-date balances." },
      { title: "Send in a Few Taps", description: "Pick a coin, type how much, choose who receives it. Check on the device. Done." },
      { title: "Pair Once, Use Forever", description: "Connect your phone to your Stasher the first time. From then on, they remember each other." },
      { title: "Full History", description: "Every transaction you have ever made, with clear status and confirmations." },
      { title: "Multiple Stashers", description: "Family savings? Personal trading? Manage as many Stashers as you want, all from one app." },
      { title: "Saved Addresses", description: "Save people you send to often. No more copying and pasting long codes — and no more mistakes." }
    ],
    downloadLinks: [
      { platform: "iOS", url: "#" },
      { platform: "Android", url: "#" }
    ]
  },

  comparison: {
    title: "HOW STASHER COMPARES",
    subtitle: "Stasher vs. Others",
    competitors: ["Ledger Nano X", "Trezor Safe 5"],
    rows: [
      { feature: "Always stays offline (never touches the internet)", stasher: "Yes", competitor1: "No", competitor2: "No" },
      { feature: "Safe against future super-computers", stasher: "Yes", competitor1: "No", competitor2: "No" },
      { feature: "Separate bridge device for the internet", stasher: "Yes", competitor1: "No", competitor2: "No" },
      { feature: "Shows every transaction on its own screen", stasher: "Yes", competitor1: "Yes", competitor2: "Yes" },
      { feature: "Needs a button press to approve", stasher: "Yes", competitor1: "Yes", competitor2: "Yes" },
      { feature: "Standard 24-word backup phrase", stasher: "Yes", competitor1: "Yes", competitor2: "Yes" },
      { feature: "Truly random, one-of-a-kind keys", stasher: "Yes", competitor1: "Yes", competitor2: "No" },
      { feature: "Backup locked behind your password", stasher: "Yes", competitor1: "Partial", competitor2: "No" },
      { feature: "Free phone app", stasher: "Yes", competitor1: "Yes", competitor2: "Yes" },
      { feature: "Coins supported", stasher: "56+", competitor1: "5,500+", competitor2: "9,000+" },
      { feature: "Version for companies", stasher: "Yes", competitor1: "Yes", competitor2: "No" },
      { feature: "Code anyone can inspect", stasher: "Yes", competitor1: "Partial", competitor2: "Yes" },
      { feature: "Protects against password guessing", stasher: "Locks out longer each try", competitor1: "Wipes after 3", competitor2: "Wipes after 16" }
    ]
  },

  openSource: {
    title: "NOTHING TO HIDE",
    subtitle: "Transparency",
    description: "We believe you should be able to check for yourself that Stasher does what it promises. That is why the code inside Stasher is public — anyone can read it, inspect it, and even improve it.",
    points: [
      { title: "Public Code", description: "The code that runs inside Stasher is on GitHub. Any expert can read every line that handles your money." },
      { title: "Build It Yourself", description: "You can build the code yourself and check that it matches what is running on your device. No hidden back doors." },
      { title: "Independent Experts Check It", description: "We pay outside security experts to inspect our code and hardware — including the future-proof protection." },
      { title: "Reward for Finding Problems", description: "We pay security researchers who find and report issues responsibly. Your safety is a team effort." }
    ]
  },

  compliance: {
    title: "READY FOR SERIOUS BUSINESS",
    description: "Stasher Enterprise meets the strict rules that banks, exchanges, and large investors need. Every action is logged. Every permission is set. Nothing happens without proof.",
    points: [
      "Ready for financial audits and regulator review",
      "Certified-grade hardware security",
      "Every action permanently logged — no deletions",
      "Future-proof security for long-term holdings",
      "Fine-grained permissions for teams and roles",
      "Instantly revoke access if someone leaves"
    ]
  },

  faq: {
    title: "FREQUENTLY ASKED QUESTIONS",
    subtitle: "FAQ",
    items: [
      {
        question: "I'm new to crypto — what exactly is Stasher?",
        answer: "Stasher is a small device — about the size of a thick credit card — that keeps your crypto safe. Think of it like a tiny safe you can carry. Your crypto lives inside the device, not on the internet, so hackers cannot steal it. You use a friendly phone app to see your balances and send money, and press a button on the device whenever you approve a move."
      },
      {
        question: "Why do I need a device? Can't I just keep my crypto in an app?",
        answer: "You can, but apps on phones and computers are connected to the internet — which means hackers, viruses, or a stolen phone can steal your crypto. A device like Stasher stays offline, so there is no way for anyone on the internet to reach your money. It's the difference between leaving cash on your desk and locking it in a safe."
      },
      {
        question: "Is Stasher hard to use if I've never done this before?",
        answer: "Not at all. If you can use a banking app, you can use Stasher. The phone app walks you through every step. To send crypto: you pick what to send, check the details on the device screen, press the button, done. No commands, no code, no complicated words."
      },
      {
        question: "What does 'quantum-safe' mean? Should I worry?",
        answer: "Most crypto wallets today rely on math that a powerful new kind of computer — called a quantum computer — will be able to break. Experts say this could happen in the next decade. Stasher uses a new kind of math that stays safe even against those future computers. You don't need to upgrade later. Your crypto is safe now AND years from now."
      },
      {
        question: "Who is Stasher for?",
        answer: "Anyone who owns crypto and wants it safe. Someone buying their first Bitcoin. Someone saving for retirement. A trader who wants safety without slowing down. A parent setting money aside for their kids' future. If you hold crypto and care about keeping it, Stasher is for you."
      },
      {
        question: "What if I lose the device?",
        answer: "Your money is completely safe. When you first set up Stasher, you write down 24 special words (your 'backup phrase'). As long as you keep those 24 words somewhere safe — ideally on paper in a drawer or a safe, not on your computer — you can restore all your crypto onto a new Stasher in minutes."
      },
      {
        question: "How is Stasher different from Ledger or Trezor?",
        answer: "Ledger and Trezor need to plug into your phone or computer when they approve a transaction — so for a moment, your crypto is close to the internet. Stasher splits this into two devices: one always stays offline with your crypto, another handles the internet. They never mix. Stasher is also built to survive future quantum computers, which Ledger and Trezor are not."
      },
      {
        question: "Which coins can I store on Stasher?",
        answer: "Over 56 popular coins, including Bitcoin, Ethereum, Solana, XRP, Litecoin, Cardano, and Polkadot. We add new ones regularly."
      },
      {
        question: "Can Stasher the company see or touch my money?",
        answer: "No. We make the device, but your crypto belongs only to you. You are the only one with the password and backup phrase. Nobody at Stasher can access, freeze, or move your money. Even if our company vanished tomorrow, your crypto would still be safe and usable."
      },
      {
        question: "What if my phone gets hacked or stolen?",
        answer: "Your crypto is still safe. The secret code that controls your money is only on the Stasher device — never on your phone. Your phone is just a screen that helps you use Stasher. A stolen or hacked phone cannot move a single coin, because nothing happens without you pressing the button on the Stasher itself."
      },
      {
        question: "How do I know the device is really trustworthy?",
        answer: "You don't have to take our word for it. The code that runs inside Stasher is public — anyone can read it on GitHub and confirm it does exactly what we promise. Independent security experts also check it for us. Nothing is hidden."
      },
      {
        question: "What is Stasher Enterprise?",
        answer: "A bigger version of Stasher for companies, exchanges, and wealthy families that manage large amounts of crypto. It uses six coordinated devices, team approval rules (for example: 'any three people must agree'), and full audit history so every action is traceable."
      }
    ]
  },

  assets: {
    title: "COINS YOU CAN STORE",
    items: ["BITCOIN", "ETHEREUM", "SOLANA", "XRP", "POLKADOT", "LITECOIN", "CARDANO", "50+ MORE"]
  },

  newsletter: {
    title: "STAY IN THE LOOP",
    description: "Launch news, helpful tips, and early access — no spam, ever.",
    placeholder: "your@email.com",
    cta: "SUBSCRIBE"
  },

  footer: {
    transmission: "END OF TRANSMISSION",
    copyright: "\u00A9 2026 STASHER // OFFLINE, QUANTUM-RESILIENT CRYPTO CUSTODY // ALL RIGHTS RESERVED",
    socials: [
      { name: "GitHub", url: "https://github.com/Crypto-Stasher", icon: <svg viewBox="0 0 24 24" fill="currentColor" width="18" height="18"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12" /></svg> },
      { name: "X", url: "#", icon: <svg viewBox="0 0 24 24" fill="currentColor" width="16" height="16"><path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z" /></svg> },
      { name: "Discord", url: "#", icon: <svg viewBox="0 0 24 24" fill="currentColor" width="18" height="18"><path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z" /></svg> },
      { name: "Telegram", url: "#", icon: <svg viewBox="0 0 24 24" fill="currentColor" width="18" height="18"><path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z" /></svg> },
      { name: "Reddit", url: "#", icon: <svg viewBox="0 0 24 24" fill="currentColor" width="18" height="18"><path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.249-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.688-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z" /></svg> },
      { name: "YouTube", url: "#", icon: <svg viewBox="0 0 24 24" fill="currentColor" width="18" height="18"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" /></svg> }
    ]
  }
};
